services:
  db:
    image: postgres:17-alpine
    container_name: campuseats_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: campuseats
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: campuseatsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U campuseats -d campuseatsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: campuseats_rabbitmq
    restart: unless-stopped
    ports:
      - "127.0.0.1:5672:5672" # optional listening port
      - "127.0.0.1:15672:15672" # optional UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: campuseats_smtp4dev
    ports:
      - "127.0.0.1:2525:25" # Integration test smtp port!
      - "127.0.0.1:5000:80" # Web UI (local hostonly)

  web:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: campuseats_web
    restart: unless-stopped
    ports:
      - "8080:8080"
    
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
      RabbitMq__Host: rabbitmq
      RabbitMq__User: guest
      RabbitMq__Password: guest
      Smtp__Host: smtp4dev
      Smtp__Port: 25
      Authentication__Google__ClientId: ${GOOGLE_CLIENT_ID}
      Authentication__Google__ClientSecret: ${GOOGLE_CLIENT_SECRET}

    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys

  notification:
    build:
      context: .
      dockerfile: src/CampusEats.Notification/Dockerfile.notification
      
    container_name: campuseats_notification
    restart: unless-stopped
      
    depends_on:
      rabbitmq:
        condition: service_healthy
    
    environment:
      RabbitMq__Host: rabbitmq
      RabbitMq__User: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
      Smtp__Host: smtp4dev
      Smtp__Port: 25


networks:
  internal:
    driver: bridge
    internal: true

volumes:
  postgres_data:
  dataprotection_keys:
